version: "3.7"

services:
  mongodb:
    container_name: node_clean_arch_mongodb
    image: mongo:4.2.3
    environment:
      MONGO_INITDB_DATABASE: db-local
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    # comment to enable mongodb logging
    logging:
      driver: none
