version: "3.7"

services:
  mongodb:
    container_name: node_clean_arch_mongodb
    image: mongo:4.2.3
    ports:
      - "27017:27017"
    # comment to enable mongodb logging
    logging:
      driver: none
